import { Yard } from "@mui/icons-material";

const products = [
    {
        nombre: "Exploding Kittens Party Pack",
        precio: "29.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/cA9HD1a.png",
        descripcion: "Se trata de una versión gatuna de la ruleta rusa con un gran componente estratégico. Los jugadores van robando cartas hasta que a alguien le sale un Exploding Kitten . Cuando esto sucede, esa persona muere y queda eliminada de la partida (a no ser que tenga una carta de Desactivación, que permite desactivar al Exploding Kitten con armas como punteros láser, friegas de barriga o bocatas de menta gatuna). El resto de las cartas de la baraja sirven para cambiar de lugar, mitigar o evitar a los Exploding Kittens.",
        youtubeLink: "https://www.youtube.com/embed/lOP8ZjkN7gc",
        stock: 10,
    },
    {
        nombre: "¡Aventureros al Tren! Europa",
        precio: "39.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/wOVrxAp.png",
        descripcion: "¡Aventureros al Tren! Europa te invita a una nueva aventura en tren a lo largo y ancho de la Europa de fin de siglo, desde las escarpadas laderas de Edimburgo hasta los soleados muelles de Constantinopla, desde los polvorientos callejones de Pamplona hasta una estación azotada por el viento en Berlín. ¿Te arriesgarás a un viaje a través de los oscuros túneles de Suiza? ¿Te subirás al ferry del Mar Negro? ¿O construirás estaciones de tren en las grandes capitales de los antiguos imperios? ¡Tu siguiente movimiento puede convertirte en el mayor magnate ferroviario de Europa!",
        youtubeLink: "https://www.youtube.com/embed/lOP8ZjkN7gc",   
        stock: 10,   
    },
    {
        nombre: "Crónicas del Crimen 1400",
        precio: "34.990",
        categoria: "Scape Room",
        img: "https://i.imgur.com/Jo44B6T.png",
        descripcion: "Año 1400. Tu nombre es Abelard Lavel, un caballero asentado en Paris. Desde niño has tenido sueños proféticos y extraños sobre crímenes del pasado y del futuro. Has conseguido usar tu poder para hacer el bien, resolviendo misterios que nadie más podría. Ahora gracias a tu creciente reputación, las gentes de Paris buscan tu ayuda. ¿Acudirás en su auxilio?",
        youtubeLink: "https://www.youtube.com/embed/0Q6ezIoYy4k",   
        stock: 10, 
    },
    {
        nombre: "Azul Pabellón de Verano",
        precio: "36.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/dUlzJ7L.png",
        descripcion: "En Azul – Pabellón de Verano, los jugadores tienen la tarea de construir los pisos de la obra maestra sin construir del Rey. Usando la misma mecánica de selección de la serie Azul, los jugadores deben seleccionar cuidadosamente los materiales más bellos y evitar el despilfarro de suministros. Sólo los mejores artesanos estarán a la altura del desafío.",
        youtubeLink: "https://www.youtube.com/embed/WOoKrjIkMxU",      
        stock: 10,
    },
    {
        nombre: "Love Letter Edición Portátil",
        precio: "12.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/fvz0iE4.png",
        descripcion: "Love Letter es un juego de riesgo, deducción y suerte, con reglas sencillas que crean interacciones dinámicas y divertidas entre los jugadores, que deberán intentar entregar su carta de amor en las manos de la Princesa mientras mantienen las cartas de otros jugadores alejadas. ¿Podrás superar a tus amigos y ganarte la confianza de la noble princesa?",
        youtubeLink: "https://www.youtube.com/embed/NQcQDyoo_H0",
        stock: 10,
    },
    {
        nombre: "7 Wonders Architects",
        precio: "39.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/ThovH27.jpg",
        descripcion: "Construye una maravilla tan grandiosa que nunca se olvide y pase a la historia. 7 Wonders Architects es un juego rápido, con reglas sencillas y una gran variedad de estrategias. 1) Elige una carta entre las tres disponibles. 2) Juégala colocándola frente a ti. 3) ¡Utiliza su capacidad para construir tu maravilla, hacer avances científicos o luchar contra tus vecinos!",
        youtubeLink: "https://www.youtube.com/embed/GgpGIjzdVIw",
        stock: 10,
    },
    {
        nombre: "Bitoku",
        precio: "62.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/cjg71Pn.jpg",
        descripcion: "En Bitoku los jugadores tomarán el papel de espíritus que habitan un bosque ancestral guardado por el gran espíritu. Su objetivo será que sus espíritus se eleven con tal de convertirse en dignos herederos del gran espíritu del bosque. El gran espíritu del bosque lleva gobernando con sabiduría y justicia la vida de todos aquellos que ahí habitan. Su paso por el mundo ha dejado huella, y el eco de sus acciones resonará durante siglos por todos los confines y rincones del bosque. Pero su tiempo está llegando a su fin. Los espíritus Bitoku del bosque elegirán cuál de ellos ha de ser aquel que le sustituya.En este juego los jugadores tomarán el papel de espíritus Bitoku del bosque en su camino hacia la trascendencia, con el objetivo de elevarse y convertirse en el próximo gran espíritu del bosque. Para ello contarán con la ayuda de los yōkai, los kodamas y los distintos peregrinos que les acompañarán en el camino.",
        youtubeLink: "https://www.youtube.com/embed/U01p8higTCI",
        stock: 10,
    },
    {
        nombre: "Bunny Kingdom",
        precio: "47.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/vVGiEGj.jpg",
        descripcion: "Bunny Kingdom es un juego de dos a cuatro jugadores, en el que serás un Señor Conejo a la conquista de un nuevo mundo en nombre del Rey Bunny. Tendrás que obtener lo mejor que esas tierras puedan ofrecer. Explorar los rincones más remotos, construir ciudades, recolectar recursos para hacer prosperar tus feudos y acumular las preciadas zanahorias doradas. No olvides complacer al rey llevando a cabo misiones, con la mayor discreción, ¡Al servicio de Su Majestad!",
        youtubeLink: "https://www.youtube.com/embed/xTn3ww2hiVk",
    },
    {
        nombre: "Carcassonne Básico (2da Edición)",
        precio: "21.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/UX73Tjy.png",
        descripcion: "Carcassonne es el juego de mesa moderno para los que quieren empezar con juegos estratégicos de verdad. Con un reglamento sencillo de aprender, cada decisión que tomas durante la partida influye en tus posibilidades de ganar. Mediante la colocación de losetas, los jugadores construyen caminos, ciudades y monasterios, y, cuando se acaban las losetas, el jugador que tiene más puntos gana la partida.",
        youtubeLink: "https://www.youtube.com/embed/b0SDEcRwOlc",
        stock: 10,
    },
    {
        nombre: "Checkpoint Charlie (2da Edición)",
        precio: "17.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/9IaROvK.jpg",
        descripcion: "Checkpoint Charlie es un juego de cartas para 2 a 6 jugadores, en el que los jugadores deben intentar ser los primeros en cruzar la frontera entre la Alemania del Este y la Alemania del Oeste. Para ello, deberán hacer uso de sus habilidades de espionaje y de su astucia para evitar que los agentes de la Stasi les descubran y les detengan. ¡El que más rápido consiga cruzar la frontera será el ganador!",
        youtubeLink: "https://www.youtube.com/embed/bTJXWgaFb3I",
        stock: 10,
    },
    {
        nombre: "Clank",
        precio: "54.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/VEvBdJq.jpg",
        descripcion: "Entra a la guarida de un Dragón enojado montaña para robar artefactos preciosos, busca para encontrar botín más valioso y adquiere cartas para aumentar el poder de tu deck… ¡Pero cuidado! Cada sonido puede despertar al Dragón.",
        youtubeLink: "https://www.youtube.com/embed/5BAXK6eI8VU",
        stock: 10,
    },
    {
        nombre: "Código Secreto",
        precio: "19.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/aDWsYRU.jpg",
        descripcion: "Código secreto es un juego en el que se mezcla la intriga, el espionaje y las claves secretas. ¡Ponte en la piel de un espía y descubre la identidad de tus compañeros! Este juego, eminentemente competitivo por equipos, requiere colaborar entre los miembros de cada bando para llegar, juntos, a la victoria. Permite partidas de 2 a 8 jugadores y una duración aproximada de 15 minutos.",
        youtubeLink: "https://www.youtube.com/embed/lMf7MnQsSNg",
        stock: 10,
    },
    {
        nombre: "Cortex Challenge +",
        precio: "24.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/d9vjOsk.png",
        descripcion: "¡Desafía a tu cerebro con un divertido juego que pondrá a prueba tu razonamiento, memoria y rapidez! Compite con los demás jugadores en 9 tipos de retos que estimularán tus habilidades cognitivas: pruebas táctiles, parejas, secuencias lógicas, laberintos, pruebas con colores…",
        youtubeLink: "https://www.youtube.com/embed/jweHQOh86vs",
        stock: 10,
    },
    {
        nombre: "Dixit Nueva Edición",
        precio: "29.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/5x5WM1I.png",
        descripcion: "En este juego ganador de numerosos premios, los jugadores usarán las bellas ilustraciones de sus cartas para engañar a sus oponentes para que encuentren la imagen correcta. Pero adivinar la carta de tus oponentes es la mitad del juego, para que ganes debes lograr que tus amigos encuentren tu carta correcta. ¡Elige bien tus palabras y prepárate para la diversión!",
        youtubeLink: "https://www.youtube.com/embed/mqBJ1eGMeeU",
        stock: 10,
    },
    {
        nombre: "Dobble Impermeable",
        precio: "14.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/3Ox5vIh.png",
        descripcion: "Dobble un juego con más de 50 símbolos, 55 cartas, con uno, y solamente un símbolo idéntico entre cada carta. ¿Serás capaz de descubrirlo? ¡Disfruta de toda la entretención de Dobble en su versión para jugar en la playa o piscina, con cartas resistentes al agua!",
        youtubeLink: "https://www.youtube.com/embed/OOO_KbYHacg",
        stock: 10,
    },
    {
        nombre: "Exit El castillo prohibido",
        precio: "12.990",
        categoria: "Scape Room",
        img: "https://i.imgur.com/ct8BcCG.jpg",
        descripcion: "De visita por un antiguo castillo, encontrarás con una magnifica sala del trono. Pero al entrar en ella, ¡el enorme portón de madera se cierra con un estrépito y los deja atrapados! ¿Podrás resolver los acertijos a tiempo y salir del castillo antes que sea demasiado tarde?.",
        youtubeLink: "https://www.youtube.com/embed/GSD2xMxYbwY",
        stock: 10,
    },
    {
        nombre: "Exit La estación polar",
        precio: "11.990",
        categoria: "Scape Room",
        img: "https://i.imgur.com/nfuu8wm.jpg",
        descripcion: "La estación polar es el sexto juego de la serie Exit y está ambientado en una estación polar de investigación científica. Los jugadores se dirigen a ella, aunque lleva algo de tiempo clausurada. Una vez dentro, empieza a sonar una alarma y los jugadores se encuentran en medio de una carrera contrarreloj para salir de la estación y conseguir huir antes de que todo el complejo vuele por los aires. Una vez más, todos los elementos del juego serán necesarios para resolver los enigmas que plantea. ¿Serán capaces de encontrar la salida?",
        youtubeLink: "https://www.youtube.com/embed/GSD2xMxYbwY",
        stock: 10,
    },
    {
        nombre: "Exit La mansión siniestra",
        precio: "12.990",
        categoria: "Scape Room",
        img: "https://i.imgur.com/7GiqBjb.jpg",
        descripcion: "Creías que la mansión que había junto a tu casa estaba deshabitada, pero acabas de encontrar una nota en tu buzón que te pide que vayas allí. Cuando entras ves que se trata de una casa señorial repleta de muebles antiguos y bien conservados. Pero tu asombro se ve interrumpido de repente cuando la puerta se cierra de golpe detrás tuyo. Un escalofrío recorre tu espalda…",
        youtubeLink: "https://www.youtube.com/embed/GSD2xMxYbwY",
        stock: 10,
    },
    {
        nombre: "Exit Vuelo hacia lo desconocido",
        precio: "11.990",
        categoria: "Scape Room",
        img: "https://i.imgur.com/GCW9iMw.jpg",
        descripcion: "Son la tripulación de un avión que sobrevuela la isla de Barbados. Todo parece normal, de hecho, habéis hecho este trayecto cientos de veces y nada podría sorprenderos ya. Sin embargo, estáis a punto de vivir la tormenta eléctrica más peligrosa de vuestras vidas. ¿Seréis capaces de reparar el avión y escapar con vida?",
        youtubeLink: "https://www.youtube.com/embed/GSD2xMxYbwY",
        stock: 10,
    },
    {
        nombre: "Ilusion",
        precio: "10.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/VCBqWTP.png",
        descripcion: "¿Confías en tus ojos? ¿Cuánto color eres capaz de ver? En eso consiste Illusion. Las reglas son tan sencillas que puedes comenzar a jugar de inmediato. Niños y niñas contra mayores, jóvenes contra adultos y adultas… ¿Quién tendrá la mejor vista y no se dejará engañar?",
        youtubeLink: "https://www.youtube.com/embed/5SMS83VRQrQ",
        stock: 10,
    },
    {
        nombre: "Jaipur",
        precio: "19.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/HBU6oXE.png",
        descripcion: "En Jaipur, el objetivo es convertirse en el mercader personal del Maharajá consiguiendo más riquezas que tu oponente al final de cada ronda. Para ello, consigue e intercambia productos en el mercado y luego véndelos para obtener rupias. Si consigues hacer una venta grande (tres cartas o más), recibirás una ficha de Bonificación.",
        youtubeLink: "https://www.youtube.com/embed/vvRwNycqKzc",
        stock: 10,
    },
    {
        nombre: "Just One (Español)",
        precio: "22.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/PAHpQW2.png",
        descripcion: "Just One es un juego cooperativo de adivinanzas para entre 4 y 7 jugadores. Su misión es averiguar cuantas más palabras secretas mejor, antes de que se acaben las cartas del mazo. Un divertido juego perfecto para toda la familia y que supone una manera divertida de mejorar habilidades como la deducción lógica y herramientas como el vocabulario, la capacidad de expresión y la síntesis.",
        youtubeLink: "https://www.youtube.com/embed/g7OCXiWscZ8",
        stock: 10,
    },
    {
        nombre: "La feria de las Pulgas",
        precio: "12.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/5gaGJTA.png",
        descripcion: "El pueblo de Titirilquén está emocionado: ha comenzado la feria de las pulgas de la ciudad. En distintos puestos se ofrecen las chucherías más llamativas. Para ganar deberás ser lo muy velóz. Debes juntar todas las chucherías de un tipo antes que el resto.",
        youtubeLink: "https://www.youtube.com/embed/Gifa-jfybbw",
        stock: 10,
    },
    {
        nombre: "La Tripulación",
        precio: "14.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/NNoOj7I.png",
        descripcion: "En este juego de bazas cooperativo, tendrás que completar 50 misiones distintas mientras viajas por el sistema solar. Pero solo tendrás éxito si consigues trabajar en equipo. Para superar los retos y completar tu misión, la comunicación será esencial; pero, en el espacio, las cosas pueden complicarse más de lo esperado…",
        youtubeLink: "https://www.youtube.com/embed/Oyawv4zKATI",
        stock: 10,
    },
    {
        nombre: "Lacrimosa",
        precio: "66.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/3TvzjVi.jpg",
        descripcion: "Wolfgang Amadeus Mozart fue una figura clave en la historia de la música occidental, que influenció a varias generaciones tras su pronto fallecimiento. Lacrimosa es un gran homenaje al compositor austríaco, que nos acerca a su vida y su obra a través de una experiencia divertida y desafiante. Este rítmico juego que nos transporta a las cortes europeas del siglo XVIII siguiendo la obra del compositor. Como auspiciador del genio austríaco, desearán ser recordados como su mayor benefactor y pasar a la historia junto a él. Para ello, deberán acabar de financiar el Réquiem que dejó inconcluso antes de su muerte y demostrar que a lo largo de su vida fueron sus más fieles seguidores.",
        youtubeLink: "https://www.youtube.com/embed/6z5dtEE8zhg",
        stock: 10,
    },
    {
        nombre: "Magic Maze en Marte",
        precio: "24.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/Q1AsetR.png",
        descripcion: "Robots especializados están construyendo cúpulas habitacionales en la superficie de Marte, para albergar a los futuros colonos. Para ello, utilizan pistas magnéticas para propulsar vacas, plátanos y cristales a gran velocidad.",
        youtubeLink: "https://www.youtube.com/embed/MC1ym-ISyCI",
        stock: 10,
    },
    {
        nombre: "Mal Trago",
        precio: "15.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/n6DXZfu.jpg",
        descripcion: "La bruja necesita conejillos de indias para probar sus nuevas pociones y nosotros, sus leales esbirros goblins, hemos sido designados como voluntarios forzosos para esta ocasión. Sigue las dinámicas y retos que te muestran las cartas. El goblin perdedor tendrá que beber. Hay jugadores que aprovechan la oportunidad de beber cada vez que su goblin lo hace…",
        youtubeLink: "https://www.youtube.com/embed/R26kSgWkVak",
        stock: 10,
    },
    {
        nombre: "Mala Leche Original",
        precio: "20.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/BJM0qxC.png",
        descripcion: "Combina los pensamientos más horribles e inmorales de nuestra enferma sociedad chilena para lograr las frases más absurdas que logran sorprender al Dealer (sea por graciosa, por absurda, por brígida, por tabú, por cercana o lo que sea). Mala Leche Original tiene mucho contenido obsceno, político, farandulero, religioso, discriminatorio, abusivo, pedófilo, sádico, racista, machista, pervertido, ñoño, xenofóbico, violento o simplemente estúpido.",
        youtubeLink: "https://www.youtube.com/embed/BtkTF_D7dRw",
        stock: 10,
    },
    {
        nombre: "Moly Atrapa",
        precio: "13.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/fbmlN7m.png",
        descripcion: "En lo profundo de los bosques chilenos una gran plaga de bichos invasores está desequilibrando el ecosistema, consumiendo los recursos y desplazando a las especies autóctonas. Por suerte, entre los habitantes del bosque, encontramos a la Molinaranea magellanica, más conocida como la araña Moly. Moly es una gran cazadora que utiliza sus colores para camuflarse entre las ramas de los árboles, en las que teje redes para cazar a incautas presas.",
        youtubeLink: "https://www.youtube.com/embed/KJGQ0Z7TyoU",
        stock: 10,
    },
    {
        nombre: "Mycelium: Descubriendo el reino fungi",
        precio: "40.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/E6LwwA4.png",
        descripcion: "Los hongos no son plantas ni animales, componen su propio reino llamado Fungi. Estos organismos son esenciales para la vida en el planeta ya que, sin los hongos, las plantas no podrían sobrevivir fuera del agua, o bien nada se descompondría. Esto, porque los dos roles principales que cumplen los hongos en la naturaleza son la de generar colaboraciones entre distintos organismos, y descomponer la materia orgánica.",
        youtubeLink: "https://www.youtube.com/embed/jR9OmWPDUTs",
        stock: 10,
    },
    {
        nombre: "Mysterium Park",
        precio: "22.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/TEwOXZz.png",
        descripcion: "Su antiguo director desapareció hace unos años, pero la investigación no llegó a ninguna conclusión. Desde esa noche, no han dejado de suceder cosas muy extrañas. Varios videntes están convencidos de que un espíritu vaga por la feria y han decidido desvelar la verdad. En este juego cooperativo, el espíritu envía visiones mediante cartas ilustradas a los videntes, que deberán interpretarlas para descartar sospechosos y lugares. Después, solo tendrán una única oportunidad para averiguar lo que realmente le ocurrió al director. Tan solo disponen de seis noches antes de que el circo abandone el pueblo.",
        youtubeLink: "https://www.youtube.com/embed/AlFjNZYEcRY",
        stock: 10,
    },
    {
        nombre: "Pandemic",
        precio: "32.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/EJqvAFd.png",
        descripcion: "Como miembros de un equipo especializado en la contención de enfermedades, deberéis controlar la expansión de cuatro plagas mortales mientras intentáis descubrir sus respectivas curas. Para conseguirlo tus compañeros y tú tendréis que viajar a lo largo y ancho del globo, tratando a los infectados y buscando los recursos necesarios para sintetizar cada una de las curas. Si queréis triunfar en esta misión, deberéis trabajar unidos. Pandemic es un juego cooperativo, lo que significa que todos los jugadores ganarán o perderán como equipo. El tiempo avanza sin descanso mientras las epidemias se suceden y nuevos brotes amenazan con extender la enfermedad. ¿Podréis encontrar las cuatro curas a tiempo? ¡El destino de la humanidad está en vuestras manos!",
        youtubeLink: "https://www.youtube.com/embed/C1M-87Xjr5o",
        stock: 10,
    },
    {
        nombre: "Photosynthesis",
        precio: "41.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/wAZS4OM.jpg",
        descripcion: "Cuatro tipos de árboles compiten por propagarse en la tierra fértil con sus semillas para atrapar la luz que les entrega el sol. Al crecer, cada árbol obtiene cierta cantidad de luz que los permite conseguir puntos de luz, que sirven para producir más semillas, pero, a mayor tamaño, también produce una sombra a árboles que estén cerca de él privándoles de la preciada luz. Al final de su ciclo, cada árbol proporcionará al jugador puntos proporcionales a la fertilidad en donde se plantó el árbol, puntos que te permitirán ganar la partida.",
        youtubeLink: "https://www.youtube.com/embed/qyQIrgldhHY",
        stock: 10,
    },
    {
        nombre: "Regicide",
        precio: "9.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/Bh5QspD.jpg",
        descripcion: "En las partidas de Regicide el compañerismo es vital, ya que si uno de los aventureros se queda sin cartas y no puede defenderse de un ataque, el juego termina automáticamente en derrota. Planead las mejores estrategias en turnos rápidos y frenéticos que harán las delicias de roleros, grupos de amigos y familias dispuestas a pasar un buen rato. También dispone de un modo solitario, por si quieres emprender el camino del guerrero sin compañía. Blandid vuestra espada o alzad el báculo para desafiar a la oscuridad en los castillos de los cuatro reinos. ¡El rey ha muerto, viva el rey!",
        youtubeLink: "https://www.youtube.com/embed/9RO1RIR0T7E",
        stock: 10,
    },
    {
        nombre: "Sherlock La Copia",
        precio: "7.990",
        categoria: "Scape Room",
        img: "https://i.imgur.com/Q5qugZZ.png",
        descripcion: "En los juegos de la Serie Sherlock Q, y partiendo de una pequeña introducción y una carta inicial, el juego nos pondrá en la piel de un grupo de detectives con un caso por investigar. Siguiendo unas sencillas reglas de juego, los investigadores deben deducir las pistas, exponer teorías y resolver el misterio.",
        youtubeLink: "https://www.youtube.com/embed/jrKrS1T8CXQ",
        stock: 10,
    },
    {
        nombre: "Simplicity",
        precio: "21.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/jkwSUcS.png",
        descripcion: "Simplicity es una ciudad que está creciendo rápidamente. Semana tras semana surgen nuevos barrios, y es urgente encontrar una persona que se encargue de planificar la ciudad. A lo largo de cinco rondas cada participante construirá en los distintos terrenos, buscando formar los barrios más convenientes para obtener puntos.",
        youtubeLink: "https://www.youtube.com/embed/-ZW9Q7CUf78",
        stock: 10,
    },
    {
        nombre: "So Clover!",
        precio: "22.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/pzUV7xK.png",
        descripcion: "So Clover! es un juego cooperativo de asociación de palabras. Colaboren en equipo para batir sus propios récords. Roben cartas de Palabra y, sin que nadie lo vea, escríbanlas en su tablero Trébol algo que tengan en común. Esas serán sus Pistas. Luego, colaboren en equipo para intentar adivinar qué Palabras tiene cada jugador. Al final de la partida, sumen todas las puntuaciones según el número de Palabras que hayan adivinado y anoten el total en el Registro de hitos. ¡Intenten superar su propio récord en cada partida!",
        youtubeLink: "https://www.youtube.com/embed/ScKCHQeFaN0",
        stock: 10,
    },
    {
        nombre: "Splendor",
        precio: "30.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/JmgEqZD.png",
        descripcion: "A lo largo de la partida, los jugadores irán cogiendo fichas de oro y piedras preciosas, con las que podrán adquirir cartas de desarrollo. Dichas cartas otorgan puntos de prestigio y bonus, los cuales permiten adquirir las siguientes cartas de desarrollo a un precio menor. Cuando un jugador posee suficientes bonus, inmediatamente recibe la visita de un noble (lo cual también reporta puntos de prestigio). Cuando un jugador llega a 15 puntos, se completa la ronda actual y el jugador con más puntos de prestigio será declarado ganador.",
        youtubeLink: "https://www.youtube.com/embed/5enAMA8zq3E",
        stock: 10,
    },
    {
        nombre: "The Mind",
        precio: "10.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/joQaGIo.png",
        descripcion: "The Mind es más que un simple juego, es un experimento, un viaje, una experiencia en equipo muy sencilla y que no podrán olvidar. Deberán superar todos los niveles para ganar la partida, aunque no podrán hablar, ponerse de acuerdo ni intercambiar información.",
        youtubeLink: "https://www.youtube.com/embed/dFGmKid9O9k",
        stock: 10,
    },
    {
        nombre: "Toma 6",
        precio: "10.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/xe9rn4g.png",
        descripcion: "Cada participante recibe 10 cartas que tendrán que jugar hábilmente en una de las cuatro filas. Pero atención, en cada fila caben solo cinco cartas, quien coloque la sexta se llevará las cinco cartas anteriores con sus puntos negativos.",
        youtubeLink: "https://www.youtube.com/embed/XxtUcUP0bOg",
        stock: 10,
    },
    {
        nombre: "Tough Calls Dystopia",
        precio: "15.990",
        categoria: "Party Game",
        img: "https://i.imgur.com/EwYg8hK.png",
        descripcion: "Juego narrativo y argumentativo ambientado diversos escenarios de ciencia ficción. Asumiremos el rol de personajes que pretenden liderar una comunidad de sobrevivientes en un mundo post-apocalíptico. Cada ronda se elegirá una pregunta que todo el grupo responderá. Luego votaremos en secreto por la mejor respuesta y quien obtenga la mayor cantidad de votos al final de la partida ganará.",
        youtubeLink: "https://www.youtube.com/embed/f-nG7zdC2E0",
        stock: 10,
    },
    {
        nombre: "Yuncos: El lado oscuro de la luz",
        precio: "13.990",
        categoria: "Estrategia",
        img: "https://i.imgur.com/Rz1kvfI.png",
        descripcion: "El Yunco (Pelecanoides garnotti) es un ave de unos 25 cm de largo, que destaca por sus increíbles habilidades para bucear. Es capaz de sumergirse hasta los 80 metros de profundidad para encontrar los peces y crustáceos que conforman su dieta. Esta ave de hábitos nocturnos y oceánicos, utiliza la luna y las estrellas para orientar su vuelo. Es por esto que la contaminación lumínica producida por las ciudades les afecta gravemente, lo que provoca choques producto de la desorientación. En este juego ayudarás al Yunco en su vuelo a conseguir comida, evitar chocar contra los obstáculos y volver a la isla de Choros a anidar.",
        youtubeLink: "https://www.youtube.com/embed/vhpkpO91_mc",
        stock: 10,
    },
  ];

  